//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pitalytics.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pitalytics.Domain.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select About Us Source].
        /// </summary>
        internal static string SelectAboutUsSourceText {
            get {
                return ResourceManager.GetString("SelectAboutUsSourceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Agent Of Deduction].
        /// </summary>
        internal static string SelectAgentOfDeduction {
            get {
                return ResourceManager.GetString("SelectAgentOfDeduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select a Role].
        /// </summary>
        internal static string SelectAppRoleText {
            get {
                return ResourceManager.GetString("SelectAppRoleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Branch].
        /// </summary>
        internal static string SelectBranch {
            get {
                return ResourceManager.GetString("SelectBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Company].
        /// </summary>
        internal static string SelectCompanyText {
            get {
                return ResourceManager.GetString("SelectCompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select the type of Degree you received].
        /// </summary>
        internal static string SelectDegreeText {
            get {
                return ResourceManager.GetString("SelectDegreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Department].
        /// </summary>
        internal static string SelectDepartmentText {
            get {
                return ResourceManager.GetString("SelectDepartmentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Experience].
        /// </summary>
        internal static string SelectExperience {
            get {
                return ResourceManager.GetString("SelectExperience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select FileType].
        /// </summary>
        internal static string SelectFileType {
            get {
                return ResourceManager.GetString("SelectFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Gender].
        /// </summary>
        internal static string SelectGenderText {
            get {
                return ResourceManager.GetString("SelectGenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Grade].
        /// </summary>
        internal static string SelectGradeText {
            get {
                return ResourceManager.GetString("SelectGradeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Income Type].
        /// </summary>
        internal static string SelectIncome {
            get {
                return ResourceManager.GetString("SelectIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Industry].
        /// </summary>
        internal static string SelectIndustry {
            get {
                return ResourceManager.GetString("SelectIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Inland Revenue].
        /// </summary>
        internal static string SelectInland {
            get {
                return ResourceManager.GetString("SelectInland", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select JobTitle].
        /// </summary>
        internal static string SelectJobTitleText {
            get {
                return ResourceManager.GetString("SelectJobTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Jurisdiction].
        /// </summary>
        internal static string SelectJurisdiction {
            get {
                return ResourceManager.GetString("SelectJurisdiction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Leave Type].
        /// </summary>
        internal static string SelectLeaveTypeText {
            get {
                return ResourceManager.GetString("SelectLeaveTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select Parent Company].
        /// </summary>
        internal static string SelectParentCompanyText {
            get {
                return ResourceManager.GetString("SelectParentCompanyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Select User].
        /// </summary>
        internal static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
    }
}
