//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pitalytics.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pitalytics.Domain.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Branch already exist.
        /// </summary>
        public static string BranchExist {
            get {
                return ResourceManager.GetString("BranchExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Company Already Exist.
        /// </summary>
        public static string CompanyExist {
            get {
                return ResourceManager.GetString("CompanyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Admin.
        /// </summary>
        public static string ContactAdmin {
            get {
                return ResourceManager.GetString("ContactAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure to verify your Email.
        /// </summary>
        public static string EmailVerified {
            get {
                return ResourceManager.GetString("EmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Income type already exist.
        /// </summary>
        public static string IncomeTypeExist {
            get {
                return ResourceManager.GetString("IncomeTypeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Type already assigned.
        /// </summary>
        public static string IncomeTypeJurisdictionExist {
            get {
                return ResourceManager.GetString("IncomeTypeJurisdictionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Password is Incorrect.
        /// </summary>
        public static string IncorrectPasswordText {
            get {
                return ResourceManager.GetString("IncorrectPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Industry Exist.
        /// </summary>
        public static string IndustryExist {
            get {
                return ResourceManager.GetString("IndustryExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Inland Revenue Exist.
        /// </summary>
        public static string InlandRevenueExist {
            get {
                return ResourceManager.GetString("InlandRevenueExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Exist.
        /// </summary>
        public static string IsEmailExist {
            get {
                return ResourceManager.GetString("IsEmailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Role Exist.
        /// </summary>
        public static string IsRolesExist {
            get {
                return ResourceManager.GetString("IsRolesExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Jurisdiction Exist.
        /// </summary>
        public static string JurisdictionExist {
            get {
                return ResourceManager.GetString("JurisdictionExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your old Password and New Password is not the same.
        /// </summary>
        public static string PasswordNotEqual {
            get {
                return ResourceManager.GetString("PasswordNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password saved successfully.
        /// </summary>
        public static string PasswordSaved {
            get {
                return ResourceManager.GetString("PasswordSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Agent .
        /// </summary>
        public static string TA {
            get {
                return ResourceManager.GetString("TA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Agent Users.
        /// </summary>
        public static string TAU {
            get {
                return ResourceManager.GetString("TAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected  Tax Authority Exist, Please contact Admin.
        /// </summary>
        public static string TaxAuthorityExist {
            get {
                return ResourceManager.GetString("TaxAuthorityExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Verified.
        /// </summary>
        public static string Verified {
            get {
                return ResourceManager.GetString("Verified", resourceCulture);
            }
        }
    }
}
