//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pitalytics.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Beneficiary
    {
        public int BeneficiaryId { get; set; }
        public int CACRegNo { get; set; }
        public string BVN { get; set; }
        public int JurisdictionId { get; set; }
        public string BeneficiaryName { get; set; }
        public bool IsActive { get; set; }
    }
}
