//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pitalytics.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncomeReport
    {
        public int IncomeReportId { get; set; }
        public Nullable<decimal> Dividends { get; set; }
        public Nullable<decimal> ProfessionalServices { get; set; }
        public Nullable<decimal> DirectorFees { get; set; }
        public Nullable<decimal> RentHire { get; set; }
        public Nullable<decimal> Interest { get; set; }
        public Nullable<decimal> Construction { get; set; }
        public Nullable<decimal> ContractOfSupplies { get; set; }
        public Nullable<decimal> ContractOfServices { get; set; }
        public Nullable<decimal> TechnicalConsultancy { get; set; }
        public Nullable<decimal> ManagementComm { get; set; }
        public Nullable<decimal> Royalty { get; set; }
        public string DateCreated { get; set; }
        public string BVN { get; set; }
        public string BeneficiaryTin { get; set; }
    }
}
