//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pitalytics.Repositories.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PitalyticsEntities : DbContext
    {
        public PitalyticsEntities()
            : base("name=PitalyticsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActionLog> ActionLogs { get; set; }
        public virtual DbSet<AdminUserTable> AdminUserTables { get; set; }
        public virtual DbSet<AgentOfDeductionBranch> AgentOfDeductionBranches { get; set; }
        public virtual DbSet<AgentOfDeductionInfo> AgentOfDeductionInfoes { get; set; }
        public virtual DbSet<AppActivityLog> AppActivityLogs { get; set; }
        public virtual DbSet<Beneficiary> Beneficiaries { get; set; }
        public virtual DbSet<Branch> Branches { get; set; }
        public virtual DbSet<BranchJurisdiction> BranchJurisdictions { get; set; }
        public virtual DbSet<DigitalFile> DigitalFiles { get; set; }
        public virtual DbSet<FileType> FileTypes { get; set; }
        public virtual DbSet<IncomeReport> IncomeReports { get; set; }
        public virtual DbSet<IncomeType> IncomeTypes { get; set; }
        public virtual DbSet<Industry> Industries { get; set; }
        public virtual DbSet<InlandRevenue> InlandRevenues { get; set; }
        public virtual DbSet<Jurisdiction> Jurisdictions { get; set; }
        public virtual DbSet<JurisdictionIncomeType> JurisdictionIncomeTypes { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleStatu> RoleStatus { get; set; }
        public virtual DbSet<TaxAuthority> TaxAuthorities { get; set; }
        public virtual DbSet<TaxReport> TaxReports { get; set; }
        public virtual DbSet<TaxReturn> TaxReturns { get; set; }
        public virtual DbSet<UserActivationCode> UserActivationCodes { get; set; }
        public virtual DbSet<UserBranch> UserBranches { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
    }
}
