//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pitalytics.Repositories.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxReturn
    {
        public int TaxReturnId { get; set; }
        public string BeneficiaryTin { get; set; }
        public string BeneficiaryName { get; set; }
        public string BVN { get; set; }
        public string BeneficiaryAddress { get; set; }
        public string InvoiceNo { get; set; }
        public System.DateTime ContractDate { get; set; }
        public string ContractDescription { get; set; }
        public string ContractAmount { get; set; }
        public string WHT_Rate { get; set; }
        public string WHT_Amount { get; set; }
        public int IncomeTypeId { get; set; }
        public int UserRegistrationId { get; set; }
        public int AgentOfDeductionId { get; set; }
        public int BranchId { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime DateCreated { get; set; }
        public int JurisdictionId { get; set; }
    }
}
